### ISSUE TITLE
cannot find bitmap.AsBmpStream method

### ISSUE THREAD

**Issue by tsiank** [jbaarssen/PdfLibCore#1]
in the PdfLibCore/src/ExampleApp/Program.cs :
`//SaveToJpeg(bitmap.AsBmpStream(196D, 196D), Path.Combine(destination, $"{i++}.jpeg"));`
I cannot find bitmap.AsBmpStream method.

**Comment by Mirsoltan** [comment]
how to use?
Why is there no documentary?

**Comment by better-999** [comment]
Why there's no one answer this issue? how to fix that?

**Comment by better-999** [comment]
This project is copy from "PDFiumSharp" project,  so this project is no 'AsBmpStream' function, this is the only one that i know.
