### ISSUE TITLE
Warning：MSB3270

### ISSUE THREAD

**Issue by EzrealJ** [jbaarssen/PdfLibCore#10]
Hello

When I import the package using nuget, I will get a warning when compiling the project

MSB3270: The generated project's processor architecture "MSIL" does not match the processor architecture "AMD64" referencing PdfLibCore.dll". This mismatch may cause runtime failures. Consider changing your project's The target processor architecture to align the processor architecture between your project and the reference, or associate a reference with a processor architecture that matches your project's target processor architecture

targetFramework: net6, aspnetcore webapi

Please how should I handle this warning

Looking forward to your reply

**Comment by Kokenberg** [comment]
We have just accepted a PR fixing this issue.
