### ISSUE TITLE
Crash when rendering a PDF to Image

### ISSUE THREAD

**Issue by Taliesin60** [jbaarssen/PdfLibCore#13]
In my WPF applicationn when I render PDF to image, I often have a crash : 
PdfLibCore.PdfiumException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée. ---> System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée.
   à PdfLibCore.Pdfium.PlatformInvoke.FPDF_RenderPageBitmap(FPDF_BITMAP bitmap, FPDF_PAGE page, Int32 start_x, Int32 start_y, Int32 size_x, Int32 size_y, PageOrientations rotate, RenderingFlags flags)
   à PdfLibCore.Pdfium.FPDF_RenderPageBitmap(FPDF_BITMAP bitmap, FPDF_PAGE page, Int32 start_x, Int32 start_y, Int32 size_x, Int32 size_y, PageOrientations rotate, RenderingFlags flags)
   
   
For rendering, I use PdfiumBitmap : 
   
var bitmap = new PdfiumBitmap(width, height, true);
pdfPage.Render(bitmap, pdfPage.Orientation, RenderingFlags.LcdText);

The crash occurs in Pdfium.cs, line 928 :

lock (Pdfium._lock)
      {
        try
        {
          Pdfium.PlatformInvoke.FPDF_RenderPageBitmap(bitmap, page, start_x, start_y, size_x, size_y, rotate, flags);
        }
        catch (AccessViolationException ex)
        {
          throw new PdfiumException((Exception) ex);
        }
      }

**Comment by Kokenberg** [comment]
We have just released a new version 2.4.0 which resolved the issue for us.
