### ISSUE TITLE
Attempted to read or write protected memory

### ISSUE THREAD

**Issue by dellos** [jbaarssen/PdfLibCore#14]
I run PDF to image converter function in MulitTask as showed below
![image](https://user-images.githubusercontent.com/5093271/209036358-b8d1ed2b-13ef-409e-8a40-e3e5182fea52.png)

And some time [Attempted to read or write protected memory] error raised. I m sure that Not use duplicate Folder Path in img.Save() function. 

![PDFBug](https://user-images.githubusercontent.com/5093271/209038033-b6d3728e-0d66-4a6c-8bd5-b47c6e29f390.jpg)

**Comment by Kokenberg** [comment]
Sorry for the late response. We've run into the same issue. We've just released a new version with updated NuGet packages (mainly the bblanchon.PDFium.Linux, bblanchon.PDFium.macOs and bblanchon.PDFium.Win32 package). This has resolved the AccessViolationExceptions for us.
