### ISSUE TITLE
how to change resolution?

### ISSUE THREAD

**Issue by Mirsoltan** [jbaarssen/PdfLibCore#2]
using (var ms = new MemoryStream())
                        {
                            img.Save(ms, ImageFormat.Jpeg);
}

By default, storage is done with 96 dpi and the quality is not good. How can I change this default to 150 or 200 Dpi to experience better quality?

**Comment by Kokenberg** [comment]
When creating a PdfiumBitmap you can get the BMPStream like so with a specific DPI:
```c#
using var bitmap = new PdfiumBitmap(pageWidth, pageHeight, true); 
pdfPage.Render(bitmap, PageOrientations.Normal, RenderingFlags.LcdText);
var stream = bitmap.AsBmpStream(200D, 200D);
```
When omitting the values in `AsBmpStream` the default value of 72dpi is used for both the X and Y axis.

When using the `AsImage` extension method you can use the same DPI 'settings'.
